name: Build Av1an (Windows x64)
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: windows-2022

    env:
      CARGO_INCREMENTAL: 0
      vsynth_ver: "R72"
      vsynth_path: "C:/Program Files/Vapoursynth"

    steps:
      - name: NASM setup
        uses: ilammy/setup-nasm@v1
        with:
          # version: 2.16.03
          from-source: false

      - name: VapourSynth installation
        run: |
          $tempFile = New-TemporaryFile
          $uri = 'https://github.com/vapoursynth/vapoursynth/releases/download/VER/VapourSynth64-Portable-VER.zip'.Replace('VER', "$env:vsynth_ver")
          Invoke-WebRequest "$uri" -OutFile "$tempFile" -TimeoutSec 10
          Expand-Archive "$tempFile" "$env:vsynth_path"

      - uses: actions/checkout@v5
      - uses: Swatinem/rust-cache@v2

      - name: Get latest commit
        id: get_commit
        shell: pwsh
        run: |
          $commit = git log -1 --pretty=format:"%h: %s (%an)"
          echo "message=$commit" >> $env:GITHUB_OUTPUT

      - name: Av1an build
        run: cargo build --release

      - name: Delete existing release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete latest --cleanup-tag

      - name: Create prerelease
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          tag_name: latest
          body: |
            Commit:
            ${{ steps.get_commit.outputs.message }}
          files: target/release/av1an.exe
          fail_on_unmatched_files: true
